//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<byte> enabled { get; set; }
        public Nullable<short> access_level { get; set; }
    }
}
